quarkus:
  datasource:
    db-kind: postgresql
    metrics:
      enabled: true
  hibernate-orm:
    log:
      queries-slower-than-ms: 100
mp:
  messaging:
    connector:
      smallrye-kafka:
        auto:
          offset:
            reset: earliest
        propagate-record-key: true
    incoming:
      prices-in:
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      prices-in2:
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
    outgoing:
      prices-out:
        connector: smallrye-kafka
        value:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
      prices-out2:
        connector: smallrye-kafka
        value:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
